// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV66e3a8noq9yIhYSwxqdNLbou9pmGUsk',
    appId: '1:530534713816:web:c486b5d4e426191b6e0aad',
    messagingSenderId: '530534713816',
    projectId: 'vize030719060',
    authDomain: 'vize030719060.firebaseapp.com',
    storageBucket: 'vize030719060.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3z9i2RyztuMhgWjxttR8hPSzibbyLmSY',
    appId: '1:530534713816:android:03d1ea88ce63b5e56e0aad',
    messagingSenderId: '530534713816',
    projectId: 'vize030719060',
    storageBucket: 'vize030719060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfEcg96cH4Z0xa4pxF0Cz6_ur9Zp0s6iE',
    appId: '1:530534713816:ios:704342b864284a446e0aad',
    messagingSenderId: '530534713816',
    projectId: 'vize030719060',
    storageBucket: 'vize030719060.appspot.com',
    iosClientId: '530534713816-rhto7nr48vigb3tiqje880ehttgoooee.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfEcg96cH4Z0xa4pxF0Cz6_ur9Zp0s6iE',
    appId: '1:530534713816:ios:704342b864284a446e0aad',
    messagingSenderId: '530534713816',
    projectId: 'vize030719060',
    storageBucket: 'vize030719060.appspot.com',
    iosClientId: '530534713816-rhto7nr48vigb3tiqje880ehttgoooee.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
